
quarkus:
  package:
    jar:
      enabled: true
      type: fast-jar
  container-image:
    builder: jib
    group: "denic0la-ocean"
    name: link-back
    tag: latest
    registry: "registry.digitalocean.com"
    push: false
#  kubernetes:
#    init-task-defaults:
#      wait-for-container:
#        image: "groundnuty/k8s-wait-for:no-root-v1.7"
  log:
    file:
      enabled: false
    socket:
      enabled: false
    console:
      json:
        enabled: true
        pretty-print: true
        print-details: true
    syslog:
      enabled: false


  flyway:
    migrate-at-start: true
  http:
    port: 8080

app:
  base-url: http://localhost:8080
