greeting:
  message: "hello"

quarkus:
  kubernetes:
    init-task-defaults:
      wait-for-container:
        image: "groundnuty/k8s-wait-for:no-root-v1.7"

  datasource:
    db-kind: postgresql
    password: devpassword
    database: devdb
    username: Developer
    jdbc:
      url: jdbc:postgresql://localhost:5432/devdb
      driver: org.postgresql.Driver

  flyway:
    migrate-at-start: true
  http:
    port: 8080

app:
  base-url: http://localhost:8080