
quarkus:
#  kubernetes:
#    init-task-defaults:
#      wait-for-container:
#        image: "groundnuty/k8s-wait-for:no-root-v1.7"
  log:
    file:
      enabled: false
    socket:
      enabled: false
    console:
      json:
        enabled: true
        pretty-print: true
        date-time-format: dd-MM-yyyy'T'HH:mm:ss.SSSXXX
        print-details: true
    syslog:
      enabled: false


  flyway:
    migrate-at-start: true
  http:
    port: 8080

app:
  base-url: http://localhost:8080
