name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    env:
      IMAGE_TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 2400
      - name: Build image
        run: |
          ./gradlew build -x test \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.tag=${{ env.IMAGE_TAG }}
      - name: Push image to DigitalOcean Container Registry
        id: push
        run: |
          docker push registry.digitalocean.com/denic0la-ocean/link-back:${{ env.IMAGE_TAG }}
          echo "digest=$(docker images --no-trunc --quiet registry.digitalocean.com/denic0la-ocean/link-back:${{ env.IMAGE_TAG }})" >> $GITHUB_OUTPUT
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: registry.digitalocean.com/denic0la-ocean/link-back
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: false